package qa.avasilev.tests;

import com.codeborne.selenide.Configuration;
import qa.avasilev.config.Project;
import qa.avasilev.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import qa.avasilev.pages.MainPage;

import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class MainTest extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("IntelliJ IDEA is downloadable from upper menu")
    void generatedTest() {

        step("Open https://www.jetbrains.com/", () -> {
            open("");
        });

        MainPage mainPage = new MainPage();

        step("Open Dev tools upper menu", () -> {
            mainPage.openDevTools();
        });

        step("Click IDEA menu item", () -> {
            mainPage.clickIdeaMenuItem();
        });

        step("Verify page", () -> {
            step("// todo: just add selenium action");
        });

        step("Open download page", () -> {
            step("// todo: just add selenium action");
        });

        step("Verify page", () -> {
            step("// todo: just add selenium action");
        });
    }
/*
    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://www.jetbrains.com/'", () ->
            open("https://www.jetbrains.com/"));

        step("Page title should have text 'JetBrains: Essential tools for software developers and teams'", () -> {
            String expectedTitle = "JetBrains: Essential tools for software developers and teams";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.jetbrains.com/'", () ->
            open()
        );

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }*/
}